config/routes.rb
Chatonline::Application.routes.draw do
  root :to => "channels#index", constraints: User
  root :to => "sessions#new", constraints: lambda { |request| !User.matches?(request) }
  
  resources :channels, :only => [ :index, :show, :create ]

  match '/auth/:provider/callback' => 'sessions#create'

  match '/signin' => 'sessions#new', :as => :signin

  match '/signout' => 'sessions#destroy', :as => :signout

  match '/auth/failure' => 'sessions#failure'

  match ':controller(/:action(/:id))(.:format)'
    

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  
  validates_presence_of :name 
  validates_uniqueness_of :name
  
  before_validation :generate_uuid

  
  private 

    def generate_uuid
      self.uuid = UUID.generate
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name, :github_id
  validates :github_id, uniqueness: true

  class << self
    def matches? request
      !request.session[:user_id].blank?
    end
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.github_id = auth['uid']
      if auth['info']
        user.name = auth['info']['nickname'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Mongoid::Errors::DocumentNotFound
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def index
    @channels = Channel.all
    @channel = Channel.new
  end

  def show
    @channel = Channel.find_by_uuid(params[:id])
  end

  def create
    @channel = Channel.find_or_create_by_name(params[:channel][:name])
    if @channel
      redirect_to channel_path(@channel.uuid)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/github'
  end


  def create
    user = User.where(:github_id => auth['uid']).first || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

  def auth
    auth = request.env["omniauth.auth"]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/channels/create.html.erb
<h1>Channels#create</h1>
<p>Find me in app/views/channels/create.html.erb</p>

app/views/channels/index.html.erb
<h5>Channel List</h5>
<div class="row">
  <ul>
    <% @channels.each do |channel| %>
      <li><%= link_to channel.name, channel_path(channel.uuid) %></li>
    <% end %>
  </ul>
</div>


<h5>Join New Channel</h5>

<%= simple_form_for @channel, html: { :class => "form-horizontal" } do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  <%= f.submit "Join" %>
<% end %>

app/views/channels/show.html.erb
<h3>Channel - <%= @channel.name %></h3>

app/views/home/index.html.erb
<h3>Home</h3>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Chatonline", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    Logged in as <%= current_user.name %>
    </li>
    <li>
    <%= link_to 'Logout', signout_path %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', signin_path %>  
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Chatonline" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>